---
- name: Display distribution
  debug:
    msg: "{{ ansible_distribution }}"

- name: Display distribution release
  debug:
    msg: "{{ ansible_distribution_release }}"

- name: Display distribution version
  debug:
    msg: "{{ ansible_distribution_version }}"

- name: Display OS family
  debug:
    msg: "{{ ansible_os_family }}"
